name: xml
version: 3.2.3

author: Lukas Renggli <renggli@gmail.com>
description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  petitparser: ^2.0.0
  collection: ^1.14.0
dev_dependencies:
  test: ^1.3.0
  args: ^1.5.0
