name: xml
version: 3.5.0

author: Lukas Renggli <renggli@gmail.com>
description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  collection: ^1.14.0
  convert: ^2.1.0
  meta: ^1.1.0
  petitparser: ^2.4.0
dev_dependencies:
  test: ^1.6.0
  args: ^1.5.0
