name: xml
version: 5.0.0-nullsafety

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  collection: ^1.15.0-nullsafety
  convert: ^2.1.0
  meta: ^1.3.0-nullsafety
  petitparser: ^4.0.0-nullsafety
dev_dependencies:
  test: ^1.16.0-nullsafety
  args: ^1.6.0
