name: xml
version: 7.0.0

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml
topics:
  - parser
  - sax
  - xml
  - xpath

environment:
  sdk: ^3.10.0
dependencies:
  collection: ^1.19.0
  meta: ^1.17.0
  petitparser: ^7.0.2
dev_dependencies:
  args: ^2.7.0
  coverage: ^1.15.0
  lints: ^6.1.0
  test: ^1.29.0