name: xml
version: 6.5.0

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml
topics:
  - parser
  - sax
  - xml
  - xpath

environment:
  sdk: ^3.2.0
dependencies:
  collection: ^1.18.0
  meta: ^1.9.0
  petitparser: ^6.0.0
dev_dependencies:
  args: ^2.4.0
  lints: ^3.0.0
  test: ^1.24.0