name: xml
version: 6.6.1

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml
topics:
  - parser
  - sax
  - xml
  - xpath

environment:
  sdk: ^3.8.0
dependencies:
  collection: ^1.19.0
  meta: ^1.16.0
  petitparser: ^7.0.0
dev_dependencies:
  args: ^2.7.0
  lints: ^6.0.0
  test: ^1.26.0
